site_name: PARC
theme: readthedocs
markdown_extensions:
    - admonition
    - abbr
    - attr_list
    - toc:
        permalink: True
        separator: "_"
plugins:
    - search
nav:
    - 'Competition Overview': 'competition-overview/index.md'

    - 'Competition Instruction': 
        - 'Phase 1: Simulation': 'competition-instruction/phase1/index.md'
        - 'Phase 2: Physical Robot': 'competition-instruction/phase2/index.md'

    - 'Getting Started Tutorials':
        - 'Setting up your PC': 'setting-up-computer/index.md'

extra_css: [theme_override.css]
